#!/usr/bin/env bash
# Display the content of the file /etc/passwd with username, user ID, and home directory path

while IFS=":" read -r username _ userid _ _ home _
do
    echo "Username: $username"
    echo "User ID: $userid"
    echo "Home Directory: $home"
done < /etc/passwd
