#!/usr/bin/env bash
# Display the content of the file /etc/passwd using a while loop and IFS

while IFS=':' read -r username _ userid groupid _ home shell
do
    echo "The user $username is part of the $groupid gang, lives in $home and rides $shell."
    echo "User ID's place is protected by the passcode PASSWORD, more info about the user here: USER $userid INFO"
done < /etc/passwd

