#!/usr/bin/env bash
# Display the time for 12 hours and 59 minutes

while [ $hour -lt 12 ]
do
    minute=1
    while [ $minute -lt 60 ]
    do
        printf "%02d:%02d\n" $hour $minute
        ((minute++))
    done
    ((hour++))
done

